name: btsa
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pystan==2.19.1.1
  - prophet==1.0.1
  - jupyter=1.0.0
  - jupyterlab=3.1.4
  - matplotlib=3.4.2
  - nb_conda_kernels
  - numpy=1.21.1
  - pandas=1.3.1
  - plotly=5.1.0
  - pymc3=3.11.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.1
  - statsmodels=0.12.2
  - pip:
    - gluonts==0.8.0
    - mxnet==1.8.0.post0
    - numpyro==0.7.2
    - sktime==0.7.0
    - torch==1.9.0
    - pytorchts==0.5.1
    - ipywidgets==7.6.3
    - bambi==0.6.0
    - tfcausalimpact
    - tensorflow
    - tensorflow-probability
